[package]
name = "no-std-tests"
edition = "2021"
publish = false
version = "0.0.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

scale-info = { workspace = true, default-features = false, features = ["bit-vec", "derive"] }
codec = { package = "parity-scale-codec", workspace = true, default-features = false, features = ["derive", "bit-vec"] }
subxt = { workspace = true, default-features = false, features = ["native"] }
subxt-metadata = { workspace = true, default-features = false }

hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
libc = { version = "0.2", default-features = false }
libc_alloc = { version = "1.0.6" }


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
