name: Rust

on:
    push:
        # Run jobs when commits are pushed to
        # master or release-like branches:
        branches:
            - master
    pull_request:
        # Run jobs for any external PR that wants
        # to merge to master, too:
        branches:
            - master

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

env:
    CARGO_TERM_COLOR: always
    # Increase wasm test timeout from 20 seconds (default) to 1 minute.
    WASM_BINDGEN_TEST_TIMEOUT: 60

jobs:
    unstable_backend_tests1:
        name: "Test (Unstable Backend) 1"
        runs-on: ubuntu-latest-16-cores
        timeout-minutes: 10
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Use substrate-node binary
              uses: ./.github/workflows/actions/use-substrate

            - name: Install Rust stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true

            - name: Rust Cache
              uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3

            - name: Run tests
              run: cargo test -p integration-tests --features unstable-backend-client -- test_lots_of_transfers_to_spot_failure --test-threads=1 --nocapture
    unstable_backend_tests2:
        name: "Test (Unstable Backend) 2"
        runs-on: ubuntu-latest-16-cores
        timeout-minutes: 10
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Use substrate-node binary
              uses: ./.github/workflows/actions/use-substrate

            - name: Install Rust stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true

            - name: Rust Cache
              uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3

            - name: Run tests
              run: cargo test -p integration-tests --features unstable-backend-client -- test_lots_of_transfers_to_spot_failure --test-threads=1 --nocapture
    unstable_backend_tests3:
        name: "Test (Unstable Backend) 3"
        runs-on: ubuntu-latest-16-cores
        timeout-minutes: 10
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Use substrate-node binary
              uses: ./.github/workflows/actions/use-substrate

            - name: Install Rust stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true

            - name: Rust Cache
              uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3

            - name: Run tests
              run: cargo test -p integration-tests --features unstable-backend-client -- test_lots_of_transfers_to_spot_failure --test-threads=1 --nocapture
