name: Rust

on:
    push:
        # Run jobs when commits are pushed to
        # master or release-like branches:
        branches:
            - master
    pull_request:
        # Run jobs for any external PR that wants
        # to merge to master, too:
        branches:
            - master

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

env:
    CARGO_TERM_COLOR: always
    # Increase wasm test timeout from 20 seconds (default) to 1 minute.
    WASM_BINDGEN_TEST_TIMEOUT: 60

jobs:

    unstable_backend_tests:
        name: "Test (Unstable Backend)"
        runs-on: ubuntu-latest-16-cores
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Use substrate-node binary
              uses: ./.github/workflows/actions/use-substrate

            - name: Install Rust stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true

            - name: Rust Cache
              uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1

            - name: Install cargo-nextest
              run: cargo install cargo-nextest

            - name: Run tests
              uses: actions-rs/cargo@v1.0.3
              with:
                  command: nextest
                  args: run --workspace --features unstable-backend-client --no-capture


    unstable_backend_tests1:
      name: "Test1 (Unstable Backend)"
      runs-on: ubuntu-latest-16-cores
      steps:
          - name: Checkout sources
            uses: actions/checkout@v4

          - name: Use substrate-node binary
            uses: ./.github/workflows/actions/use-substrate

          - name: Install Rust stable toolchain
            uses: actions-rs/toolchain@v1
            with:
                profile: minimal
                toolchain: stable
                override: true

          - name: Rust Cache
            uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1

          - name: Install cargo-nextest
            run: cargo install cargo-nextest

          - name: Run tests
            uses: actions-rs/cargo@v1.0.3
            with:
                command: nextest
                args: run --workspace --features unstable-backend-client --no-capture

    unstable_backend_tests2:
      name: "Test2 (Unstable Backend)"
      runs-on: ubuntu-latest-16-cores
      steps:
          - name: Checkout sources
            uses: actions/checkout@v4

          - name: Use substrate-node binary
            uses: ./.github/workflows/actions/use-substrate

          - name: Install Rust stable toolchain
            uses: actions-rs/toolchain@v1
            with:
                profile: minimal
                toolchain: stable
                override: true

          - name: Rust Cache
            uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1

          - name: Install cargo-nextest
            run: cargo install cargo-nextest

          - name: Run tests
            uses: actions-rs/cargo@v1.0.3
            with:
                command: nextest
                args: run --workspace --features unstable-backend-client --no-capture

                
    unstable_backend_tests3:
      name: "Test3 (Unstable Backend)"
      runs-on: ubuntu-latest-16-cores
      steps:
          - name: Checkout sources
            uses: actions/checkout@v4

          - name: Use substrate-node binary
            uses: ./.github/workflows/actions/use-substrate

          - name: Install Rust stable toolchain
            uses: actions-rs/toolchain@v1
            with:
                profile: minimal
                toolchain: stable
                override: true

          - name: Rust Cache
            uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1

          - name: Install cargo-nextest
            run: cargo install cargo-nextest

          - name: Run tests
            uses: actions-rs/cargo@v1.0.3
            with:
                command: nextest
                args: run --workspace --features unstable-backend-client --no-capture

    unstable_backend_tests4:
      name: "Test4 (Unstable Backend)"
      runs-on: ubuntu-latest-16-cores
      steps:
          - name: Checkout sources
            uses: actions/checkout@v4

          - name: Use substrate-node binary
            uses: ./.github/workflows/actions/use-substrate

          - name: Install Rust stable toolchain
            uses: actions-rs/toolchain@v1
            with:
                profile: minimal
                toolchain: stable
                override: true

          - name: Rust Cache
            uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1

          - name: Install cargo-nextest
            run: cargo install cargo-nextest

          - name: Run tests
            uses: actions-rs/cargo@v1.0.3
            with:
                command: nextest
                args: run --workspace --features unstable-backend-client --no-capture

    unstable_backend_tests6:
        name: "Test6 (Unstable Backend)"
        runs-on: ubuntu-latest-16-cores
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
  
            - name: Use substrate-node binary
              uses: ./.github/workflows/actions/use-substrate
  
            - name: Install Rust stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
  
            - name: Rust Cache
              uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1
  
            - name: Install cargo-nextest
              run: cargo install cargo-nextest
  
            - name: Run tests
              uses: actions-rs/cargo@v1.0.3
              with:
                  command: nextest
                  args: run --workspace --features unstable-backend-client --no-capture

    unstable_backend_tests9:
      name: "Test9 (Unstable Backend)"
      runs-on: ubuntu-latest-16-cores
      steps:
          - name: Checkout sources
            uses: actions/checkout@v4

          - name: Use substrate-node binary
            uses: ./.github/workflows/actions/use-substrate

          - name: Install Rust stable toolchain
            uses: actions-rs/toolchain@v1
            with:
                profile: minimal
                toolchain: stable
                override: true

          - name: Rust Cache
            uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1

          - name: Install cargo-nextest
            run: cargo install cargo-nextest

          - name: Run tests
            uses: actions-rs/cargo@v1.0.3
            with:
                command: nextest
                args: run --workspace --features unstable-backend-client --no-capture

    unstable_backend_tests7:
      name: "Test7 (Unstable Backend)"
      runs-on: ubuntu-latest-16-cores
      steps:
          - name: Checkout sources
            uses: actions/checkout@v4

          - name: Use substrate-node binary
            uses: ./.github/workflows/actions/use-substrate

          - name: Install Rust stable toolchain
            uses: actions-rs/toolchain@v1
            with:
                profile: minimal
                toolchain: stable
                override: true

          - name: Rust Cache
            uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1

          - name: Install cargo-nextest
            run: cargo install cargo-nextest

          - name: Run tests
            uses: actions-rs/cargo@v1.0.3
            with:
                command: nextest
                args: run --workspace --features unstable-backend-client --no-capture

    unstable_backend_tests8:
      name: "Test8 (Unstable Backend)"
      runs-on: ubuntu-latest-16-cores
      steps:
          - name: Checkout sources
            uses: actions/checkout@v4

          - name: Use substrate-node binary
            uses: ./.github/workflows/actions/use-substrate

          - name: Install Rust stable toolchain
            uses: actions-rs/toolchain@v1
            with:
                profile: minimal
                toolchain: stable
                override: true

          - name: Rust Cache
            uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1

          - name: Install cargo-nextest
            run: cargo install cargo-nextest

          - name: Run tests
            uses: actions-rs/cargo@v1.0.3
            with:
                command: nextest
                args: run --workspace --features unstable-backend-client --no-capture
                        
  